# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\guojiaqi\AppData\Local\TotalCMD10\Tools\自制脚本\Rename-Tool\RenameToolui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_window(object):
    def setupUi(self, window):
        window.setObjectName("window")
        window.resize(538, 392)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(window.sizePolicy().hasHeightForWidth())
        window.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/新前缀/ico.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        window.setWindowIcon(icon)
        window.setStyleSheet("\n"
"QPushButton{\n"
"    border-radius: 5;\n"
"    border-style:solid;\n"
"    border-width:1;\n"
"    border-color:rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border-color:rgb(255, 0, 0);\n"
"    color:rgb(170, 0, 0);\n"
"    background-color:rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    border-color:rgb(255, 0, 0);\n"
"    background-color:qlineargradient(spread:pad, x1:0, y1:0.7, x2:0, y2:1, stop:1 rgba(170, 0, 0, 255), stop:0 rgba(255,255,255, 255));\n"
"    color:rgb(170, 0, 0);\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(window)
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.pb2 = QtWidgets.QPushButton(window)
        self.pb2.setObjectName("pb2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.pb2)
        self.label = QtWidgets.QLabel(window)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.sBox_1 = QtWidgets.QSpinBox(window)
        self.sBox_1.setMinimum(1)
        self.sBox_1.setObjectName("sBox_1")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.sBox_1)
        self.label_2 = QtWidgets.QLabel(window)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.sBox_2 = QtWidgets.QSpinBox(window)
        self.sBox_2.setMinimum(1)
        self.sBox_2.setObjectName("sBox_2")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.sBox_2)
        self.label_3 = QtWidgets.QLabel(window)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.sBox_3 = QtWidgets.QSpinBox(window)
        self.sBox_3.setMinimum(1)
        self.sBox_3.setObjectName("sBox_3")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.sBox_3)
        self.gridLayout.addLayout(self.formLayout_2, 4, 0, 1, 1)
        self.table = QtWidgets.QTableWidget(window)
        self.table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table.setProperty("showDropIndicator", False)
        self.table.setShowGrid(True)
        self.table.setGridStyle(QtCore.Qt.DashLine)
        self.table.setRowCount(3)
        self.table.setColumnCount(3)
        self.table.setObjectName("table")
        self.table.horizontalHeader().setCascadingSectionResizes(True)
        self.table.horizontalHeader().setDefaultSectionSize(150)
        self.table.verticalHeader().setVisible(True)
        self.table.verticalHeader().setDefaultSectionSize(30)
        self.table.verticalHeader().setSortIndicatorShown(False)
        self.gridLayout.addWidget(self.table, 3, 1, 2, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pb3 = QtWidgets.QPushButton(window)
        self.pb3.setObjectName("pb3")
        self.verticalLayout.addWidget(self.pb3)
        self.pb1 = QtWidgets.QPushButton(window)
        self.pb1.setObjectName("pb1")
        self.verticalLayout.addWidget(self.pb1)
        self.te = QtWidgets.QTextEdit(window)
        self.te.setStyleSheet("")
        self.te.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.te.setObjectName("te")
        self.verticalLayout.addWidget(self.te)
        self.gridLayout.addLayout(self.verticalLayout, 3, 0, 1, 1)
        self.pb_do = QtWidgets.QPushButton(window)
        self.pb_do.setObjectName("pb_do")
        self.gridLayout.addWidget(self.pb_do, 6, 1, 1, 1)
        self.le = QtWidgets.QLineEdit(window)
        self.le.setObjectName("le")
        self.gridLayout.addWidget(self.le, 2, 0, 1, 2)
        self.pb_input = QtWidgets.QPushButton(window)
        self.pb_input.setObjectName("pb_input")
        self.gridLayout.addWidget(self.pb_input, 6, 0, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 2)

        self.retranslateUi(window)
        QtCore.QMetaObject.connectSlotsByName(window)

    def retranslateUi(self, window):
        _translate = QtCore.QCoreApplication.translate
        window.setWindowTitle(_translate("window", "rename-Tool-文件改名工具-2023-03   V1.3@Terrasky+7"))
        self.pb2.setText(_translate("window", "[C] 定义计数器"))
        self.label.setText(_translate("window", "起步："))
        self.label_2.setText(_translate("window", "步长："))
        self.label_3.setText(_translate("window", "位数："))
        self.pb3.setText(_translate("window", "[N]    原文件名"))
        self.pb1.setText(_translate("window", "[L]  文件名列表"))
        self.te.setHtml(_translate("window", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.te.setPlaceholderText(_translate("window", "输出列表文件名"))
        self.pb_do.setText(_translate("window", "生成"))
        self.le.setPlaceholderText(_translate("window", "输出文件名规则"))
        self.pb_input.setText(_translate("window", "导入文件名"))
import RenameToolrec
